default: &default
  encoding: utf8
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  adapter: mysql2
  username: root
  password:
  host: localhost
  database: protospace_41459_development  # データベース名をprotospace_41459_developmentに変更

test:
  <<: *default
  adapter: mysql2
  username: root
  password:
  host: localhost
  database: protospace_41459_test  # データベース名をprotospace_41459_testに変更
  
production:
  <<: *default
  adapter: postgresql
  encoding: unicode
  database: protospace_41459_production
  pool: 5
  username: admin
  password:  # パスワードは設定しない
  host: localhost
  port: 5432